packgs <- c("broom", "colourpicker", "dplyr", "ggplot2", "gpclib", "lubridate", "maptools", 
    "tidyr", "raster", "rgeos", "shiny", "shinyWidgets")
renv::install(packgs)
library(broom)
library(colourpicker)
library(dplyr)
library(ggplot2)
library(gpclib)
library(lubridate)
library(maptools)
library(tidyr)
library(raster)
library(rgeos)
library(shiny)
library(shinyWidgets)
renv::snapshot()
